name: python

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: python hello.py
      
    


  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: .
